version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    logging:
      driver: "none"
